# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8dac7f8d4006f8dccc94dbe45d32fa47768c069b92a772eda03e938b653b01d68eb2fb2c68025fae32ce4767d4a51771b0caea976a736f0c82fbd33be8db480

test:
  secret_key_base: 6730e122a571bad6adfbb7862ea8ab5f74458064ec69dac46df8ffc373fdaf8a77d298911deef1965fa7ccffe3890d84b4ad1c0ea181c7d2e2ea1cae491575db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
